tryber/sd-010-a-project-trivia-react-redux

package-lock.json
package.json
src/index.js
src/store/index.js

[Grupo 22] Iniciando configuração do Redux

---

src/App.js
src/pages/Login.js

Implementação da tela de login com validação para habilitar o botão de entrar no jogo.

[Main Group 14] - Feat: req.01

---

package-lock.json
package.json
src/App.css
src/App.js
src/index.js
src/pages/Login.js
src/reducers/index.js
src/store/index.js

TRIVIA - Requisitos: 
Tela de início/login
Tela de jogo
Tela de feedback
Tela de ranking
Extra não avaliativo: Tela de configurações

GRUPO 3 [Alexandre, Débora Passos, Marcos Albuquerque, Felipe Araujo, Nathalia Zebral]

---

package-lock.json
package.json
src/App.css
src/App.js
src/pages/Login/index.js
src/pages/Login/styles.css
src/services/api.js

Requisito 1
Criar a tela de login contendo as informações de nome e email, onde a pessoa que joga deve conseguir escrever seu nome e email nos inputs e o botão de jogar deve estar desabilitado caso não tenha alguma dessas informações.

Requisito 1 - Tela de login

---

src/pages/Login.jsx
src/pages/Settings.jsx

[group-26]-renzosev-req3

---

package-lock.json
package.json
src/App.js
src/App.test.js
src/actions/index.js
src/index.css
src/index.js
src/pages/Login.js
src/reducers/index.js
src/store/index.js

Main Group 24 - Req1

---

src/pages/Game.jsx
src/pages/Login.jsx
src/redux/actions/addUser.js
src/redux/actions/index.js
src/redux/reducer/index.js
src/redux/reducer/user.js

[group-26]-renzosev-req4

---

src/pages/Login/index.js
src/pages/Login/styles.css

**Requisito 2 - Crie o botão de iniciar o jogo**
O botão "Jogar" deve fazer requisição para a API para obter o _token_ e redirecionar a pessoa para tela de jogo

Requisito 2 - Tela de login

---

package-lock.json
package.json
src/index.js
src/redux/reducers/index.js
src/redux/reducers/user.js
src/redux/store/index.js

[feat] =>  initial structure of react-redux ⚛️ 

---

package-lock.json
package.json
src/actions/tokenAction.js
src/index.js
src/pages/Login/index.jsx
src/pages/Settings/index.jsx
src/reducers/index.js
src/reducers/tokenReducer.js
src/services/fetchTokenAPI.js
src/store/index.js

[GRUPO 20] (Req2) Requisição da API de token

---

package-lock.json
package.json
src/App.js
src/Pages/Login.js
src/Pages/login.css
src/actions/index.js
src/reducers/index.js
src/store/index.js

Implementa a pagina de login com os inputs para captura do nome e e-mail, salvando-os no state local do componente através do setState. 
@samuelvanguarda @carolvpinheiro

[Group 22] Pages login - Feat req 1

---

src/App.js
src/pages/Game.js
src/pages/Login.js

Button that save the token in localStorage, and after this redirect for the page Game.

Main Group 24 - Req2

---

package-lock.json
package.json

@reduxjs/toolkit, styled-components, react-transition-group and react-icons

build(packages): :package: add project packages

---

src/App.css
src/components/routes.js
src/pages/Login.js
src/pages/Settings.js
src/services/dataApi.js

v2 pq ia dar o merge na main sem querer, ai deletei.

[ Group 17 ] Req3 refactoring v2

---

src/App.js
src/actions/tokenAction.js
src/pages/Game/components/Header.jsx
src/pages/Game/index.jsx
src/pages/Login/index.jsx
src/reducers/index.js
src/reducers/tokenReducer.js

Ao iniciar o jogo, um header exibe a imagem, vinda do Gravatar, da pessoa que está jogando. Além disso, também são exibidos nome e pontuação atual. Isso permitirá o ranqueamento de _players_ futuramente.
Quando os dados são inseridos na tela inicial, o estado global da aplicação recebe um _token_ vindo da API de Trivia e guarda os dados da pessoa usuária. A tela do jogo recebe esses dados via props e os renderiza.

[GRUPO 20] (Req4) Header - Tela de jogo/trivia

---

src/App.js
src/Componentes/Header.js
src/Pages/Feedback.js

Elaboração do método que verifica a pontuação e manda a mensagem de feedback na page Feedback
@maria-baeta  @samuelvanguarda

[Grupo 22] Requisito 13

---

src/Pages/Feedback.js

Elaboração de uma section com os feedbacks sobre a pontuação final do jogador e o número de acertos
@maria-baeta  @samuelvanguarda

[Grupo 22] Requisito 14

---

package-lock.json
package.json
src/App.js
src/Pages/Feedback.js
src/Pages/Ranking.js

Implementação de dois buttons de redirecionamento, um para a página de login e outro para a de ranking, na page Feedback.
@maria-baeta @samuelvanguarda

[Grupo 22] Requisitos 15 e 16

---

src/Componentes/Header.js
src/Componentes/header.css
src/Pages/Feedback.js
src/Pages/feedback.css

elaboração do css do componente Header

[Grupo 22] Header css

---

src/actions/index.js
src/components/routes.js
src/pages/Game.js
src/pages/Login.js
src/services/dataApi.js

Resolução dos requisitos 5 e 6

Main group 17 req 5 e 6

---

src/App.js
src/components/Header.js
src/components/MultipleTypeQuest.js
src/components/QuestCard.js
src/pages/Feedback.js
src/pages/GameScreen.js
src/pages/Login.js
src/redux/actions/index.js
src/redux/reducers/login.js

░░░░░░░░░░░░░░░░░░░░
░▄▀▄▀▀▀▀▄▀▄░░░░░░░░░
░█░░░░░░░░▀▄░░░░░░▄░
█░░▀░░▀░░░░░▀▄▄░░█░█
█░▄░█▀░▄░░░░░░░▀▀░░█
█░░▀▀▀▀░░░░░░░░░░░░█
█░░░░░░░░░░░░░░░░░░█
█░░░░░░░░░░░░░░░░░░█
░█░░▄▄░░▄▄▄▄░░▄▄░░█░
░█░▄▀█░▄▀░░█░▄▀█░▄▀░
░░▀░░░▀░░░░░▀░░░▀░░░

[GRUPO 1] Reqs -> 4, 5, 6, 12

---

src/Pages/Ranking.js

Implementa um ranking visual gerado através de um objeto-exemplo ordenado em decrescente. 
Implementa um botão que redireciona para a página inicial.
@carolvpinheiro  @maria-baeta

[Group 22] Page Ranking - Req 17 e 18

---

src/Pages/Login.js
src/Pages/login.css

Corrige as rotas da página de Login.
@samuelvanguarda  @carolvpinheiro

[Group 22] Corrige erro de rotas da pagina de login

---

src/Api/index.js
src/Componentes/Header.js
src/Pages/Game.js
src/Pages/Login.js
src/Pages/login.css

Implementa lógica do componente Header(Cabeçalho) da nossa aplicação. 
- Exibe o nome do jogador;
- Exibe avatar a partir de requisição a Api do Gravatar;
- Exibe score(pontuação) zerada.
@carolvpinheiro @samuelvanguarda

[Group 22] Pages Game - Feat - requisito 4

---

src/pages/GamePage.js

Marina Alane, sua ideia deu certinho!! =)))

[ Requisito 5]: Grupo 2 - ajustes - renderização aleatória das respostas

---

package-lock.json
src/components/Login.js
src/components/Question.js
src/services/setLocalStorage.js

With this feature the token of user is saved on local storage.

Feat: Saving token on Local Storage

---

package-lock.json
package.json
src/components/Header.js
src/pages/Game.js
src/pages/Login.js

Main group 24 requirement 4 Feat

---

src/pages/DisplayGame/DisplayGame.js

Main group 25 - requirement 8

---

src/components/Button.jsx
src/components/Loading.jsx
src/components/Question.jsx
src/components/QuestionText.js
src/pages/GamePage.js

Pessoal, requisito 11 ainda em construção. Já temos a lógica de mudança de página, componentização de buttons e da pergunta do Trivia. Adicionei tbm as referências consultadas para chegar na estratégia.

[Requisito 11] - Group 2

---

src/pages/Game/components/Questions/index.jsx

Ao carregar a tela do jogo, um countdown se inicia em 30 segundos, de forma decrescente, assim a pessoa usuária precisa responder a pergunta dentro desse intervalo. Os botões de resposta são desabilitados em 5 segundos após o countdown chegar a zero, e as respostas reveladas.

[GRUPO 20] Tela de jogo - timer

---

src/components/TriviaGame.jsx

[GRUPO 21] Requisito 10

---

src/Componentes/PlayGame.js

Renderiza uma pergunta por vez.
@carolvpinheiro @samuelvanguarda

[Group 22] Pages Games - Requisito 10 - Renderiza uma pergunta por vez

---

src/Componentes/playGames.css

[Group 22] Requisito 6

---

src/actions/gameActions.js
src/pages/Game/components/Header.jsx
src/pages/Game/components/Questions/functions/localStorage.js
src/pages/Game/components/Questions/index.jsx
src/reducers/gameReducer.js

O placar inicia no _global state_ em zero, quando a pessoa usuária obtem um acerto, o placar no _global state_ e o placar no _local storage_ são atualizados. 
Quando a primeira pergunta é renderizada, o _local storage_ recebe os dados iniciais. Ao avanço das questões, o _local storage_ é atualizado ou não, dependendo do desempenho da pessoa jogadora.

[GRUPO 20] Placar do jogo

---

src/App.jsx
src/components/Countdown.jsx
src/helper/localStorage.js
src/pages/Feedback.jsx
src/pages/Game.jsx
src/pages/Login.jsx
src/pages/game.css
src/redux/actions/addPlayer.js
src/redux/actions/addScore.js
src/redux/actions/addTime.js
src/redux/actions/index.js
src/redux/reducer/game.js
src/redux/reducer/index.js
src/redux/reducer/player.js
src/services/level.js

[group-26]-pollyana-req9-req10-req11

---

src/components/Header.js
src/css/Header.css
src/services/gravatarApi.js

Implementei a API do Gravatar pra pegar a imagem de perfil no `<Header >` do `Game.js`

[ Grupo 31 ] - Gravatar

---

cypress/integration/project.spec.js
src/App.test.js
src/PAGES/Game.jsx
src/REDUX/Reducers/PlayerReducer.jsx
src/components/Header.jsx

[Main group 16] Requisito 9

---

cypress/integration/project.spec.js
src/components/MultipleTypeQuest.js
src/components/QuestCard.js
src/pages/GameScreen.js

feat: next button without resetting time

---

src/actions/gameActions.js
src/pages/Game/components/Header.jsx
src/pages/Game/components/Questions/functions/localStorage.js
src/pages/Game/components/Questions/index.jsx
src/reducers/gameReducer.js

Atenção time: está passando no teste porém as respostas não estão atualizando quando aperta o button 'Próxima'.

[Group 20] - Implement Next Buttonn

---

src/App.js
src/pages/Feedback/index.jsx
src/pages/Game/components/Questions/index.jsx

[Group 20]  (Req11) Implement 5 questions

---

src/App.js
src/PAGES/Feedback.jsx

[ Group 16 ] Requisito 12

---

src/Pages/Login.js

Concerta o Requisito 9.
@carolvpinheiro @maria-baeta

[Group 22] Page Game - Fix: Req 9

---

cypress/integration/project.spec.js
package-lock.json
src/App.jsx
src/pages/Feedback.jsx
src/pages/Game.jsx
src/pages/Ranking.jsx

[group-26]-renzosev-req12/13/14/15/16

---

src/App.js
src/pages/GameScreen.js

⡏⠉⠉⠉⠉⠉⠉⠋⠉⠉⠉⠉⠉⠉⠋⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠙⠉⠉⠉⠹
⡇⢸⣿⡟⠛⢿⣷⠀⢸⣿⡟⠛⢿⣷⡄⢸⣿⡇⠀⢸⣿⡇⢸⣿⡇⠀⢸⣿⡇⠀
⡇⢸⣿⣧⣤⣾⠿⠀⢸⣿⣇⣀⣸⡿⠃⢸⣿⡇⠀⢸⣿⡇⢸⣿⣇⣀⣸⣿⡇⠀
⡇⢸⣿⡏⠉⢹⣿⡆⢸⣿⡟⠛⢻⣷⡄⢸⣿⡇⠀⢸⣿⡇⢸⣿⡏⠉⢹⣿⡇⠀
⡇⢸⣿⣧⣤⣼⡿⠃⢸⣿⡇⠀⢸⣿⡇⠸⣿⣧⣤⣼⡿⠁⢸⣿⡇⠀⢸⣿⡇⠀
⣇⣀⣀⣀⣀⣀⣀⣄⣀⣀⣀⣀⣀⣀⣀⣠⣀⡈⠉⣁⣀⣄⣀⣀⣀⣠⣀⣀⣀⣰
⣇⣿⠘⣿⣿⣿⡿⡿⣟⣟⢟⢟⢝⠵⡝⣿⡿⢂⣼⣿⣷⣌⠩⡫⡻⣝⠹⢿⣿⣷
⡆⣿⣆⠱⣝⡵⣝⢅⠙⣿⢕⢕⢕⢕⢝⣥⢒⠅⣿⣿⣿⡿⣳⣌⠪⡪⣡⢑⢝⣇
⡆⣿⣿⣦⠹⣳⣳⣕⢅⠈⢗⢕⢕⢕⢕⢕⢈⢆⠟⠋⠉⠁⠉⠉⠁⠈⠼⢐⢕⢽
⡗⢰⣶⣶⣦⣝⢝⢕⢕⠅⡆⢕⢕⢕⢕⢕⣴⠏⣠⡶⠛⡉⡉⡛⢶⣦⡀⠐⣕⢕
⡝⡄⢻⢟⣿⣿⣷⣕⣕⣅⣿⣔⣕⣵⣵⣿⣿⢠⣿⢠⣮⡈⣌⠨⠅⠹⣷⡀⢱⢕
⡝⡵⠟⠈⢀⣀⣀⡀⠉⢿⣿⣿⣿⣿⣿⣿⣿⣼⣿⢈⡋⠴⢿⡟⣡⡇⣿⡇⡀⢕
⡝⠁⣠⣾⠟⡉⡉⡉⠻⣦⣻⣿⣿⣿⣿⣿⣿⣿⣿⣧⠸⣿⣦⣥⣿⡇⡿⣰⢗⢄
⠁⢰⣿⡏⣴⣌⠈⣌⠡⠈⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣬⣉⣉⣁⣄⢖⢕⢕⢕
⡀⢻⣿⡇⢙⠁⠴⢿⡟⣡⡆⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣵⣵⣿
⡻⣄⣻⣿⣌⠘⢿⣷⣥⣿⠇⣿⣿⣿⣿⣿⣿⠛⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣷⢄⠻⣿⣟⠿⠦⠍⠉⣡⣾⣿⣿⣿⣿⣿⣿⢸⣿⣦⠙⣿⣿⣿⣿⣿⣿⣿⣿⠟
⡕⡑⣑⣈⣻⢗⢟⢞⢝⣻⣿⣿⣿⣿⣿⣿⣿⠸⣿⠿⠃⣿⣿⣿⣿⣿⣿⡿⠁⣠
⡝⡵⡈⢟⢕⢕⢕⢕⣵⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣶⣿⣿⣿⣿⣿⠿⠋⣀⣈⠙
⡝⡵⡕⡀⠑⠳⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠛⢉⡠⡲⡫⡪⡪⡣

Grupo 1  -> req11

---

src/PAGES/Feedback.jsx
src/PAGES/Game.jsx
src/components/Header.jsx

[Grupo 16] Requisitos 12, 13 e 14

---

src/App.js
src/PAGES/Feedback.jsx

[Grupoe 16] Requisito 15

---

src/actions/index.js
src/components/Questions.js
src/components/Timer.js
src/reducers/index.js
src/reducers/timer.js

Main group 24 req8

---

src/App.js
src/pages/Feedback.js
src/pages/GameScreen.js
src/pages/Ranking.js
src/redux/actions/index.js
src/redux/reducers/login.js
src/redux/reducers/score.js

[Grupo 1] ->  Merge: 11 to 18 :shipit: 

---

src/components/Header.jsx

add span tag to receive score value

[main-group-5] req 12 fix.  Add span tag to receive score value

---

src/App.js
src/actions/index.js
src/css/Login.css
src/pages/Feedback.jsx
src/pages/Game.js
src/pages/Ranking.jsx
src/reducers/player.js

Requisitos 12, 13, 14, 15 e 16

[Grupo 31] Feedback

---

src/components/FeedbackHeader.jsx
src/components/FeedbackMsg.jsx
src/components/feedbackResult.jsx
src/components/routes.js
src/pages/Feedback.jsx

[Group 30] - Feedback screen

---

src/actions/index.js
src/pages/GamePlay.jsx
src/pages/Login.js
src/pages/Ranking.jsx
src/pages/Settings.jsx
src/reducers/playerReducer.js
src/reducers/triviaReducer.js

Reverts tryber/sd-010-a-project-trivia-react-redux#352

Revert "[Group - 27][Requisitos 19, 20, 21] Base pronta"

---

src/Componentes/PlayGame.js
src/Componentes/Timer.js
src/Componentes/playGame.css
src/actions/index.js
src/reducers/trivia.js

setamos um estado global para o timer, mas ainda estamos desenvolvendo a lógica para manipular o time

[Grupo 22] Fix Requisito 8

---

src/components/Header.js
src/pages/Game.js

[ grupo 14 ] Feat: (req10)

---

src/Componentes/PlayGame.js

Requisito 9: Para resolver o conflito tive que desmembrar a função que dava a cor para ambos os botões, certos e errados e fazer dois métodos praticamente iguais, em que apenas a função da resposta certa chama o método de adicionar a pontuação para o localhoast.
Requisito 11: Na própria função nextQuestion, fiz uma regra de negócio utilizando o index em que criamos o caminho para a pg de feedback e reiniciamos a página.
**@maria-baeta  @samuelvanguarda**

[Grupo 22] Fix Requisito 9 e 11

---

src/actions/index.js
src/components/Questions.js
src/components/Timer.js
src/pages/Game.js
src/reducers/timer.js
src/services/api.js

requisito 9 - atualizar score no localstorage

Main group 24 req9

---

src/actions/index.js
src/components/Button.jsx
src/components/Header.js
src/components/Question.jsx
src/components/Timer.jsx
src/pages/GamePage.js
src/pages/Settings.js
src/reducer/userReducer.js
src/services/shuffle.js

[Requisitos 8 e 9 - completos] Main Group 2 

---

src/App.js
src/components/Question.jsx
src/pages/Feedback.js
src/pages/GamePage.js
src/pages/Ranking.js

[ Tela Feedback - Reqs 12 -16 ] Group 2

---

package-lock.json
package.json
src/components/Boolean.jsx
src/components/Questions.jsx

Vlw pela dica! João Nascimento! :)

fix question

---

src/Componentes/PlayGame.js
src/Componentes/Timer.js
src/actions/index.js
src/reducers/trivia.js

Correção do Css do botão de resposta depois de respondidas. 

[Group 22] Pages Game Fix Css

---

src/Componentes/PlayGame.js
src/Componentes/Timer.js
src/actions/index.js
src/reducers/trivia.js

Implementa a logica do cronometro e desabilita os botões quando o valor chegar a 0;

[Group 22 ] Pages Game fix req 8

---

src/App.js
src/pages/Feedback.js
src/pages/Ranking.js

Requisito 16 - botão que leva a pagina de ranking

Main group 24 req16

---

src/Componentes/PlayGame.js

Correção do requisito 10, o botão de próximo só aparece ao fim do cronometro ou após escolher uma das alternativas.
@carolvpinheiro @samuelvanguarda

Fix - Requisito 10

---

src/Componentes/PlayGame.js

Resolução de conflitos - Req 10/16

---

src/App.js
src/actions/index.js
src/actions/manageQuestions.js
src/components/Header.js
src/components/Question.js
src/components/routes.js
src/pages/Feedback.js
src/pages/Game.js
src/pages/Ranking.js
src/reducers/game.js
src/reducers/player.js
src/reducers/questions.js

[ Group 17 ] Feat: req 16 & 18

---

src/Componentes/Header.js
src/Pages/Feedback.js
src/Pages/Ranking.js

Finalização do projeto sem o css. 
Refatoração do requisito 17.

[Group 22] pages ranking fix req 17

---

src/Componentes/Header.js
src/Pages/Feedback.js

Corrige os requisitos 12 e 14, finalizamos! 

Correção req 12 e 14

---

src/pages/Feedback.js
src/pages/Login.js
src/pages/Ranking.js

Requisitos 17 e 18 da página de ranking - a branch era inicialmente só para o requisito 17, mas para passar no teste ele depende do 18 estar feito também (apenas um botão)

Main group 24 req 17 & 18

---

src/Pages/Login.js
src/Pages/feedback.css
src/Pages/login.css

Estilização da pagina de Login

Main group 22 pages login css

---

src/actions/index.js
src/pages/Feedback.jsx
src/pages/Ranking.jsx
src/reducers/index.js
src/reducers/ranking.js

Página ainda sem estilização implementada.

[Group 33] Requisito 17 - Ranking
